name: BuildDeploy

on:
  workflow_dispatch:
  release:
    types:
    - published

jobs:
  build:
    name: Build Wheels for Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a wheel and tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}