name: BuildWheels

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Wheels for Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a wheel and tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: dist/*
    